spring:
  main:
    banner-mode: off

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/test_db
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 9000

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    log4j.logger.org.hibernate.SQL: debug
    log4j.logger.org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.sql: debug
