spring:
  main:
    banner-mode: off

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/test_db
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

server:
  port: 9000
