DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;



CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    username   VARCHAR(64)                              NOT NULL,
    email      VARCHAR(64)                              NOT NULL,
    first_name VARCHAR(64)                              NOT NULL,
    last_name  VARCHAR(64)                              NOT NULL,
    enabled    BOOLEAN                                  NOT NULL
);
CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER  REFERENCES users(id),
    name VARCHAR(64) NOT NULL
);

